/** Browser-only explorer; shared state, escaping, provider and persistence helpers live in workspace-ui. */
export const COHORT_EXPLORER_CSS = `
.cohort-sections{display:flex;gap:8px;flex-wrap:wrap;margin:18px 0}.cohort-sections button[aria-pressed=true]{background:var(--ink);color:white;border-color:var(--ink)}.explorer-controls{display:grid;grid-template-columns:1fr 1fr;gap:14px;margin-bottom:16px}.explorer-controls .field{margin:0}.persona-group{margin:18px 0}.persona-group h3{font-size:13px;color:var(--muted)}.persona-grid{align-items:start}.persona-tile .open-cue{margin-top:12px;color:var(--blue);font-weight:650}.pagination{display:flex;justify-content:space-between;align-items:center;gap:12px;margin-top:18px;flex-wrap:wrap}.persona-story{font-size:15px;line-height:1.8;white-space:pre-wrap;overflow-wrap:anywhere}.persona-facts{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,220px),1fr));gap:16px;margin:18px 0}.persona-facts>div{min-width:0;border-bottom:1px solid var(--line);padding-bottom:12px}.persona-facts dt{font-size:11px;font-weight:700;color:var(--muted);margin-bottom:5px}.persona-facts dd{font-size:13px;margin:0;white-space:pre-wrap;overflow-wrap:anywhere}.persona-detail-grid{display:grid;grid-template-columns:minmax(0,1fr) 270px;gap:18px;align-items:start}.persona-detail-grid aside{display:grid;gap:14px}.weight-summary{font:400 30px Georgia,serif;margin:8px 0}.distribution-chart{display:grid;gap:8px;margin:18px 0}.distribution-row{display:grid;grid-template-columns:minmax(100px,1fr) minmax(90px,3fr) 100px;align-items:center;gap:12px;width:100%;border:0;background:none;color:var(--ink);font:inherit;font-size:12px;padding:5px;text-align:left;cursor:pointer}.distribution-row:hover{background:var(--blue-soft)}.distribution-label{overflow-wrap:anywhere}.distribution-track{height:18px;background:var(--blue-soft);border-radius:3px;overflow:hidden}.distribution-fill{display:block;height:100%;background:var(--teal);min-width:0}.distribution-number{text-align:right;font-variant-numeric:tabular-nums}.chart-key{display:flex;gap:16px;flex-wrap:wrap;font-size:12px;color:var(--muted)}.target-summary{width:100%;border-collapse:collapse;font-size:12px}.target-summary th,.target-summary td{padding:9px 8px;text-align:left;border-bottom:1px solid var(--line)}.target-scroll{overflow:auto}.target-bucket{display:grid;grid-template-columns:2fr 1fr 1fr 1fr auto;gap:10px;align-items:start;margin:12px 0}.target-bucket.categorical{grid-template-columns:2fr 2fr 1fr auto}.target-bucket button{margin-top:20px}.source-empty{border-left:3px solid var(--teal);padding:12px 16px;background:var(--teal-soft);font-size:12px;line-height:1.6}.persona-regeneration{margin-top:18px}.persona-comparison{display:grid;grid-template-columns:1fr 1fr;gap:18px}.persona-comparison>div{min-width:0}.persona-comparison h3{font-size:13px}.cohort-brief-summary{color:var(--muted);font-size:12px}.attribute-json{font:inherit;white-space:pre-wrap;margin:0;overflow-wrap:anywhere}.distribution-caption{font-size:12px;color:var(--muted)}
[data-theme=sepia] .cohort-sections button[aria-pressed=true]{background:var(--ink);color:var(--paper);border-color:var(--ink)}

.segment-weights{border:1px solid var(--line);border-radius:8px;overflow:hidden;margin:18px 0 0}.segment-weight-row{display:grid;grid-template-columns:minmax(0,1fr) 110px 80px;align-items:center;gap:16px;padding:14px 16px;border-bottom:1px solid var(--line)}.segment-weight-row:last-child{border-bottom:0}.segment-weight-name{min-width:0}.segment-weight-name strong{display:block;font-size:13px;overflow-wrap:anywhere}.segment-weight-name small{color:var(--muted);font-size:11px}.segment-share-input{display:flex;align-items:center;gap:7px}.segment-share-input input{text-align:right;font-variant-numeric:tabular-nums;height:38px}.segment-share-input span{color:var(--muted)}.segment-weight-row .button{justify-self:end}.weights-footer{display:flex;justify-content:space-between;gap:16px;align-items:center;flex-wrap:wrap;margin-top:16px}.weights-total{font-size:12px;color:var(--muted);font-variant-numeric:tabular-nums}.weights-total[data-invalid=true]{color:var(--red)}.segment-details{margin-top:18px;padding-top:18px;border-top:1px solid var(--line)}.segment-details h3{margin:0;font-size:14px}.segment-details .panelhead{margin-bottom:14px}.segment-details .field:last-child{margin-bottom:0}
@media(max-width:600px){.segment-weight-row{grid-template-columns:minmax(0,1fr) 90px;gap:8px 12px;padding:12px}.segment-weight-row .button{grid-column:1;grid-row:auto;justify-self:start}.segment-share-input{grid-column:2;grid-row:span 2}.weights-footer{align-items:flex-start}.segment-weight-name strong{font-size:12px}}

@media(max-width:750px){.persona-detail-grid,.persona-comparison{grid-template-columns:1fr}.target-bucket,.target-bucket.categorical{grid-template-columns:1fr 1fr}.target-bucket button{margin-top:0}.distribution-row{grid-template-columns:minmax(70px,1fr) minmax(70px,2fr) 85px;gap:7px}.explorer-controls{grid-template-columns:1fr}.cohort-sections{gap:6px}.cohort-sections .button{padding-inline:9px}}
`;

export const COHORT_EXPLORER_CLIENT = String.raw`
const insights=(()=>{const __name=value=>value;return (__COHORT_INSIGHTS_FACTORY__)()})();
function cohortFieldLabel(key){if(key==='age')return 'Age';if(key==='segment')return 'Segment';return key.replace(/^attributes\./,'').replace(/([a-z])([A-Z])/g,'$1 $2').replace(/[_.]/g,' ').replace(/\b\w/g,c=>c.toUpperCase())}
function valueText(value){return value===null||value===undefined?'Not specified':Array.isArray(value)?value.map(v=>typeof v==='object'?JSON.stringify(v):String(v)).join(', '):typeof value==='object'?JSON.stringify(value,null,2):String(value)}
function personaValue(p,field){return field.split('.').reduce((value,key)=>value&&typeof value==='object'&&Object.hasOwn(value,key)?value[key]:undefined,p)}
function percent(value){return Number(value||0).toLocaleString('en-US',{maximumFractionDigits:1})+'%'}
function resetExplorer(){S.segmentId=null;S.personaOpen=false;S.personaPage=0;S.personaFilter=null;S.personaGroup='';S.cohortSection='people';S.targetDraft=null;S.personaRegenOpen=false}
function cohortSections(){return '<nav class="cohort-sections" aria-label="Cohort sections">'+[['people','Personas'],['distributions','Distributions & targets'],['weights','Weights'],['sources','Sources'],['definition','Cohort brief']].map(([key,label])=>'<button class="button" aria-pressed="'+(S.cohortSection===key)+'" data-act="cohort-section" data-section="'+key+'">'+label+'</button>').join('')+'</nav>'}
function cohortExplorer(c){
  const section=S.cohortSection||'people';
  const overview='<div class="chart-key"><span>'+c.personas.length+' synthetic personas</span><span>'+c.segments.length+' segments</span><span>'+c.sources.length+' source documents</span></div>';
  let body;
  if(section==='distributions')body=cohortDistributions(c);
  else if(section==='weights')body=segmentsEditor(c)+'<p class="subtle">To change one person’s influence within a group, open their persona.</p>';
  else if(section==='sources')body=cohortSourceNote(c)+sourcesEditor(c);
  else if(section==='definition')body=panel('Cohort prompt','Describe the audience. Generate personas, then review and edit them.','<form data-form="cohort">'+field('Cohort name','name',c.name)+field('Target population','population',c.population)+area('Generation prompt','generationPrompt',c.generationPrompt||'','The brief used to generate this cohort.','4')+area('Description','description',c.description)+area('Assumptions · one per line','assumptions',c.assumptions.join('\n'))+'<div class="row"><button class="button soft" type="submit">Apply cohort details</button><button class="button primary" type="button" data-act="generate-personas">Regenerate personas</button></div></form>');
  else body=personasExplorer(c);
  return overview+cohortSections()+body;
}

function segmentShares(c){const total=c.segments.reduce((sum,s)=>sum+Math.max(0,s.weight),0);if(!total)return c.segments.map(()=>0);const units=c.segments.map(s=>Math.round(Math.max(0,s.weight)/total*100000000)),largest=units.indexOf(Math.max(...units));units[largest]+=100000000-units.reduce((sum,n)=>sum+n,0);return units.map(n=>n/1000000)}
function applySegmentShares(c,form){const data=new FormData(form),before=segmentShares(c),shares=c.segments.map((s,i)=>{const raw=data.get('segmentShare'+i),value=Number(raw);if(raw===null||String(raw).trim()===''||!Number.isFinite(value)||value<0||value>100)throw Error('Enter a percentage from 0 to 100 for every segment.');return value});if(Math.abs(shares.reduce((sum,n)=>sum+n,0)-100)>0.000001)throw Error('Segment shares must total 100%. Adjust the percentages before applying.');if(shares.every((value,i)=>value===before[i]))return;c.segments.forEach((s,i)=>{s.weight=shares[i]/100;if(shares[i]!==before[i])s.weightBasis='user'})}
function updateSegmentTotal(form){const values=[...form.querySelectorAll('[data-segment-share]')].map(el=>el.value.trim()===''?NaN:Number(el.value)),total=values.reduce((sum,n)=>sum+n,0),valid=values.every(n=>Number.isFinite(n)&&n>=0&&n<=100)&&Math.abs(total-100)<=0.000001;const output=form.querySelector('[data-weights-total]');if(output){output.textContent=Number.isFinite(total)?'Total '+Number(total.toFixed(6))+'%'+(valid?'':' · adjust to 100%'):'Enter every percentage';output.dataset.invalid=String(!valid)}}
function segmentDetails(c,s){return '<section class="segment-details" aria-label="Segment details"><div class="panelhead"><h3 tabindex="-1">'+esc(s.label||'New segment')+'</h3><button type="button" class="button small" data-act="close-segment">Close details</button></div><form data-form="segment" data-id="'+attr(s.id)+'" data-weight-basis="'+attr(s.weightBasis)+'">'+field('Segment name','segmentLabel',s.label,'text','','required',s.id)+area('Description','segmentDescription',s.description,'','2',s.id)+select('weightBasis',[{value:'sourced',label:'Supported by sources'},{value:'assumed',label:'Assumed'},{value:'user',label:'Set by me'}],s.weightBasis,'Share based on',s.id)+(c.sources.length?'<details class="advanced" data-detail-key="segment-sources-'+attr(s.id)+'"><summary>Supporting sources'+(s.sourceIds.length?' ('+s.sourceIds.length+')':'')+'</summary>'+sourceChecks(c,s.sourceIds)+'</details>':'<p class="subtle">No sources attached. Add evidence in the Sources tab.</p>')+'<details class="advanced" data-detail-key="segment-id-'+attr(s.id)+'"><summary>Advanced</summary>'+field('Segment ID','segmentId',s.id,'text','','required',s.id)+'</details><div class="toolbar"><button class="button soft" type="submit">Apply details</button><button type="button" class="button small danger" data-act="remove-segment" data-id="'+attr(s.id)+'">Remove segment</button></div></form></section>'}
function segmentsEditor(c){const shares=segmentShares(c),selected=c.segments.find(s=>s.id===S.segmentId);const rows=c.segments.map((s,i)=>{const people=c.personas.filter(p=>p.segment===s.id).length;return '<div class="segment-weight-row"><div class="segment-weight-name"><strong>'+esc(s.label||'New segment')+'</strong><small>'+people+' '+(people===1?'persona':'personas')+' · '+({sourced:'Source-backed',assumed:'Assumed',user:'Set by you'}[s.weightBasis]||'Assumed')+'</small></div><label class="segment-share-input"><input name="segmentShare'+i+'" data-segment-share type="number" min="0" max="100" step="any" required aria-label="'+attr((s.label||'New segment')+' share (%)')+'" value="'+shares[i]+'"><span aria-hidden="true">%</span></label><button type="button" class="button small" data-act="edit-segment" data-id="'+attr(s.id)+'" aria-expanded="'+(s.id===S.segmentId)+'" aria-label="Edit '+attr(s.label||'new segment')+' details">Details</button></div>'}).join('');return panel('Segment shares','Set how much each group contributes to study results. Percentages must total 100%.',(c.segments.length?'<form data-form="segment-shares"><div class="segment-weights">'+rows+'</div><div class="weights-footer"><span class="weights-total" data-weights-total role="status">Total '+Number(shares.reduce((n,s)=>n+s,0).toFixed(6))+'%</span><button class="button soft" type="submit">Apply weights</button></div></form>':'<p class="subtle">Add a segment to define your cohort’s groups.</p>')+(selected?segmentDetails(c,selected):'')+'<div class="toolbar"><button type="button" class="button small" data-act="add-segment">＋ Add segment</button></div>')}

function cohortSourceNote(c){return '<div class="source-empty">'+(c.sources.length?'These documents support only the facts described in their notes. Synthetic biographies remain modeled profiles; attached sources are not evidence that these people exist.':'No research sources are attached. The drafting model generated these personas from your brief without browsing. Their biographies, attributes, and weights are synthetic assumptions. Add source documents and attach them to the traits or segments they support; source links are never fabricated.')+'</div>'}
function personaCard(c,p,weights){const share=weights.find(x=>x.personaId===p.id)?.weight||0;return '<button class="persona-tile" data-act="open-persona" data-id="'+attr(p.id)+'"><span class="persona-avatar">'+esc((p.label||'VP').split(/\s+/).slice(0,2).map(x=>x[0]).join(''))+'</span><strong>'+esc(p.label)+'</strong><small>'+esc(c.segments.find(s=>s.id===p.segment)?.label||p.segment)+' · age '+p.age+'</small><p>'+esc(p.background)+'</p><small>'+percent(share*100)+' effective share · '+(p.sourceIds.length?p.sourceIds.length+' attached sources':'Synthetic · no sources attached')+'</small><small class="open-cue">Read full persona →</small></button>'}
function personasExplorer(c){
  const fields=insights.discoverFields(c),weights=insights.effectiveWeights(c);
  let people=c.personas;if(S.personaFilter)people=people.filter(p=>insights.matchesBucket(p,S.personaFilter.field,S.personaFilter.bucket));
  const group=S.personaGroup||'';if(group)people=[...people].sort((a,b)=>valueText(personaValue(a,group)).localeCompare(valueText(personaValue(b,group)),undefined,{numeric:true}));
  const pages=Math.max(1,Math.ceil(people.length/24));S.personaPage=Math.min(S.personaPage||0,pages-1);
  const visible=people.slice(S.personaPage*24,(S.personaPage+1)*24),groups=new Map();for(const p of visible){let key=group?valueText(personaValue(p,group)):'';if(group==='segment')key=c.segments.find(s=>s.id===p.segment)?.label||key;if(!groups.has(key))groups.set(key,[]);groups.get(key).push(p)}
  const controls='<div class="explorer-controls">'+select('personaGroup',[{value:'',label:'No grouping'},...fields.map(f=>({value:f.field,label:cohortFieldLabel(f.field)}))],group,'Group personas by')+'<div><p class="subtle">Select a person to read their full background, inspect attributes, adjust weight, or regenerate that individual.</p><button class="button small" data-act="new-persona">＋ Add persona</button></div></div>';
  const filter=S.personaFilter?'<p class="notice">Showing '+esc(cohortFieldLabel(S.personaFilter.field))+': '+esc(S.personaFilter.bucket.label)+' <button class="button small" data-act="persona-clear-filter">Show all personas</button></p>':'';
  const cards=[...groups].map(([label,rows])=>'<section class="persona-group">'+(label?'<h3>'+esc(label)+'</h3>':'')+'<div class="persona-grid">'+rows.map(p=>personaCard(c,p,weights)).join('')+'</div></section>').join('');
  return panel('Personas','Synthetic people, with complete profiles and explicit weighting.',controls+filter+(cards||'<p class="subtle">No matching personas.</p>')+'<div class="pagination"><span class="subtle">'+(people.length?(S.personaPage*24+1)+'–'+Math.min((S.personaPage+1)*24,people.length):'0')+' of '+people.length+' personas</span><div class="row"><button class="button small" data-act="persona-page" data-delta="-1" '+(S.personaPage===0?'disabled':'')+'>Previous page</button><button class="button small" data-act="persona-page" data-delta="1" '+(S.personaPage>=pages-1?'disabled':'')+'>Next page</button></div></div>');
}
function personaFacts(p){return '<dl class="persona-facts">'+Object.entries(p.attributes).map(([key,value])=>'<div><dt>'+esc(cohortFieldLabel(key))+'</dt><dd>'+esc(valueText(value))+'</dd></div>').join('')+'</dl>'}
function personaSourceDetails(c,p){const sources=c.sources.filter(s=>p.sourceIds.includes(s.id));return sources.length?sources.map(s=>'<div class="source-line"><a href="'+attr(safeUrl(s.url))+'" target="_blank" rel="noopener noreferrer">'+esc(s.title)+'</a><p>'+esc(s.notes)+'</p><small>Retrieved '+esc(s.retrievedAt.slice(0,10))+'</small></div>').join(''):'<p class="subtle">No source documents are attached to this persona. Its profile is synthetic; no research was fetched during generation.</p>'}
function safeUrl(url){try{const u=new URL(url);return ['http:','https:'].includes(u.protocol)&&!u.username&&!u.password?url:'#'}catch{return '#'}}
function personaEditForm(c,p){return '<form data-form="persona"><fieldset '+(S.localLoading||S.localJob?.status==='running'?'disabled':'')+' style="border:0;padding:0;margin:0;min-width:0"><div class="grid2">'+field('Profile label','personaLabel',p.label)+field('Adult age','age',p.age,'number','','min="18" max="120" step="1" required')+select('segment',c.segments.map(s=>({value:s.id,label:s.label})),p.segment,'Segment')+'</div>'+area('Background','background',p.background,'The full story used by study evaluations.','7')+area('Structured attributes · JSON','attributes',JSON.stringify(p.attributes,null,2),'All named profile details. Numeric values support histogram views.','8')+area('Synthetic fields · one per line','syntheticFields',p.syntheticFields.join('\n'),'Modeled attributes, distinguished from source-backed facts.','3')+'<div class="field"><label>Attached sources</label>'+sourceChecks(c,p.sourceIds)+'</div><input type="hidden" name="personaWeight" value="'+attr(p.weight)+'"><input type="hidden" name="personaId" value="'+attr(p.id)+'"><div class="row"><button class="button soft" type="submit">Apply persona edits</button><button class="button danger" type="button" data-act="remove-persona" data-id="'+attr(p.id)+'">Remove persona</button></div></fieldset></form>'}
function personaDetail(c){const p=c.personas.find(x=>x.id===S.personId);if(!p){S.personaOpen=false;return cohorts()}const index=c.personas.indexOf(p),share=insights.effectiveWeights(c).find(x=>x.personaId===p.id)?.weight||0;
  const actions='<span id="cohortSaveState" class="save-state" role="status">'+(S.dirty?'Unsaved changes':'All changes saved')+'</span><div class="row">'+saveButton()+'<button class="button" data-act="persona-step" data-delta="-1" '+(!index?'disabled':'')+'>Previous persona</button><button class="button" data-act="persona-step" data-delta="1" '+(index===c.personas.length-1?'disabled':'')+'>Next persona</button></div>';
  const body=panel('Background','Full persona story.','<p class="persona-story">'+esc(p.background)+'</p>')+panel('Attributes','Explicit profile data; missing traits are not inferred.',personaFacts(p)||'<p class="subtle">No structured attributes yet.</p>')+'<details class="advanced" data-detail-key="persona-edit"><summary>Edit persona details</summary>'+personaEditForm(c,p)+'</details>'+personaRegeneration(c,p);
  const side=panel('Weight','How much this person contributes.','<p class="weight-summary">'+percent(share*100)+'</p><p class="subtle">Effective share of the modeled population.</p><form data-form="persona-weight"><fieldset '+(S.localLoading||S.localJob?.status==='running'?'disabled':'')+' style="border:0;padding:0;margin:0;min-width:0">'+field('Relative persona weight','relativeWeight',p.weight,'number','Normalized within '+(c.segments.find(s=>s.id===p.segment)?.label||p.segment)+'.','min="0" step="any" required')+'<button class="button soft" type="submit">Apply weight</button></fieldset></form>')+panel('Sources','Evidence attached to this profile.',personaSourceDetails(c,p)+'<button class="button small" data-act="persona-sources">Manage cohort sources</button>')+panel('Synthetic fields','Modeled details, not observations.','<p class="subtle">'+esc(p.syntheticFields.join(', ')||'No fields marked. Review provenance before using this profile.')+'</p>');
  return '<div class="cohort-detail-page">'+focusedHeader(p.label,'Age '+p.age+' · '+(c.segments.find(s=>s.id===p.segment)?.label||p.segment),'Persona '+(index+1)+' of '+c.personas.length,'persona-back','Back to cohort',actions)+'<div class="persona-detail-grid"><div>'+body+'</div><aside>'+side+'</aside></div></div>';
}
function personaReviewMetadata(c,p){return '<p class="subtle">Age '+p.age+' · Segment '+esc(c.segments.find(s=>s.id===p.segment)?.label||p.segment)+' · Relative weight '+p.weight+'</p><h4>Source references</h4>'+personaSourceDetails(c,p)+'<p class="subtle">Synthetic fields: '+esc(p.syntheticFields.join(', '))+'</p>'}
function personaRegeneration(c,p){const job=S.localJob?.persona?.cohortId===c.id&&S.localJob?.persona?.personaId===p.id?S.localJob:null;
  if(!S.personaRegenOpen&&!job)return '<div class="toolbar"><button class="button" data-act="persona-regenerate-open">Regenerate this persona</button></div>';
  const engines=S.localEngines||[],blocked=S.dirty||S.remoteRevision!==null||S.localLoading||S.localJob?.status==='running'||!draftReady();
  let proposal='';
  if(job?.status==='running')proposal='<p role="status" class="notice">'+esc(job.message)+'</p><button class="button" data-act="assistant-cancel">Cancel generation</button>';
  else if(job?.status==='completed'&&job.proposal){const replacement=job.proposal.document.cohorts.find(x=>x.id===c.id)?.personas.find(x=>x.id===p.id);if(replacement)proposal='<div class="persona-comparison"><div><h3>Current persona</h3><strong>'+esc(p.label)+'</strong><p class="persona-story">'+esc(p.background)+'</p>'+personaFacts(p)+personaReviewMetadata(c,p)+'</div><div><h3>Proposed replacement</h3><strong>'+esc(replacement.label)+'</strong><p class="persona-story">'+esc(replacement.background)+'</p>'+personaFacts(replacement)+personaReviewMetadata(c,replacement)+'</div></div><p class="subtle">'+esc(job.proposal.explanation)+'</p><div class="row"><button class="button primary" data-act="persona-adopt" '+(S.dirty||S.revision!==job.revision||S.remoteRevision!==null?'disabled':'')+'>Use replacement persona</button><button class="button" data-act="assistant-discard">Discard replacement</button></div>'}
  else if(job)proposal='<p class="warning" role="status">'+esc(job.message)+'</p>';
  const controls='<form data-form="persona-regeneration">'+area('Replacement instructions','personaRegenPrompt',S.personaRegenPrompt||'','Optional direction for a new individual. ID, segment, and weight stay unchanged.','3')+select('localEngine',engines.map(e=>({value:e.id,label:e.label+(e.available?' · ready':' · unavailable')})),S.localEngine,'Generate with')+chatGptControls()+(S.dirty?'<p class="warning">Save cohort edits before generating a replacement.</p>':'')+'<button class="button primary" data-act="persona-regenerate" type="button" '+(blocked?'disabled':'')+'>Generate replacement persona</button></form>'+(S.localError?'<p class="warning" role="alert">'+esc(S.localError)+'</p>':'');
  return panel('Regenerate one persona','Review before replacing. Every other person remains unchanged.',controls+proposal);
}
async function startPersonaJob(){if(!project())throw Error('Open a project first.');if(S.dirty||S.remoteRevision!==null)throw Error('Save your edits and resolve workspace changes before regenerating.');if(!draftReady()||S.localLoading||S.localJob?.status==='running')return;const c=cohort(),p=c.personas.find(x=>x.id===S.personId);if(!p)return;S.localLoading=true;S.localStarting=true;S.localError=null;S.proposalApplied=false;render();try{S.localJob=await api('/api/agent/jobs','POST',{projectId:S.projectId,engine:S.localEngine,...(S.localEngine==='chatgpt'?{model:S.chatgptModel}:{}),prompt:(S.personaRegenPrompt||'Generate a different, plausible individual for this cohort. Keep the cohort brief and target distributions in mind.').trim(),revision:S.revision,persona:{cohortId:c.id,personaId:p.id}});rememberLocalJob(S.localJob.id);if(S.localJob.status==='running')void pollLocalJob(S.localJob.id)}catch(error){S.localError=error instanceof Error?error.message:String(error)}finally{S.localLoading=false;S.localStarting=false;if(showingLocalJob())render()}}
function adoptPersonaProposal(){const job=S.localJob;if(job?.projectId&&job.projectId!==S.projectId)throw Error('Open the project that generated this draft.');if(job?.status!=='completed'||!job.persona||!job.proposal)return;if(S.dirty||S.revision!==job.revision||S.remoteRevision!==null)throw Error('Workspace changed. Generate a fresh replacement before applying.');const c=S.doc.cohorts.find(x=>x.id===job.persona.cohortId),p=job.proposal.document.cohorts.find(x=>x.id===c?.id)?.personas.find(x=>x.id===job.persona.personaId);if(!c||!p)throw Error('Replacement persona is missing.');const index=c.personas.findIndex(x=>x.id===p.id);if(index<0)throw Error('Original persona no longer exists.');c.personas[index]=clone(p);S.dirty=true;S.plan=null;S.localJob=null;S.personaRegenOpen=false;S.proposalApplied=true;rememberLocalJob(null);render();say('Replacement applied to draft. Save changes to keep it.')}
function cohortDistributions(c){const fields=insights.discoverFields(c);if(!fields.some(f=>f.field===S.distributionField))S.distributionField='age';const field=S.distributionField||'age',weighted=!!S.distributionWeighted,result=insights.distribution(c,field,weighted),targets=c.distributionTargets||[];
  const controls='<div class="explorer-controls">'+select('distributionField',fields.map(f=>({value:f.field,label:cohortFieldLabel(f.field)})),field,'Distribution of')+select('distributionMeasure',[{value:'count',label:'Persona count'},{value:'weighted',label:'Effective population share'}],weighted?'weighted':'count','Measure')+'</div>';
  const chart='<div class="distribution-chart" role="group" aria-label="'+attr(cohortFieldLabel(field))+' distribution">'+result.buckets.map((b,i)=>'<button class="distribution-row" data-act="distribution-drill" data-index="'+i+'" title="Inspect personas in this group"><span class="distribution-label">'+esc(field==='segment'?c.segments.find(s=>s.id===b.value)?.label||b.label:b.label)+'</span><span class="distribution-track"><span class="distribution-fill" style="width:'+Math.max(0,Math.min(100,b.percent))+'%"></span></span><span class="distribution-number">'+b.count+' · '+percent(b.percent)+'</span></button>').join('')+'</div>';
  const description='<p class="distribution-caption">'+(weighted?'Shares use segment weights × normalized persona weights.':'Counts describe the generated cohort, not a measured human population.')+' Select a bar to inspect its personas. '+result.missing+' missing values.</p><p class="subtle">Available fields come from explicit structured attributes. Ethnicity, country, or other missing traits are not guessed from names or biographies.</p>';
  const tools='<div class="row"><button class="button soft" data-act="target-edit">Set target for '+esc(cohortFieldLabel(field))+'</button><button class="button" data-act="target-new">Add another target dimension</button></div>';
  return panel('Explore distributions','Group every available numeric or categorical profile attribute.',controls+chart+description+(result.warning?'<p class="warning">'+esc(result.warning)+'</p>':'')+tools)+(S.targetDraft?targetEditor():'')+panel('Target distributions','Targets control persona counts during regeneration. Population weights remain separate.',targetOverview(c,targets)+'<div class="toolbar"><button class="button primary" data-act="generate-personas">Regenerate cohort with targets</button></div><p class="subtle">Save target edits first. Generation creates a proposal for review; it never silently replaces your cohort.</p>');
}
function targetOverview(c,targets,readonly=false){if(!targets.length)return '<p class="subtle">No target distributions set. Use an existing histogram or add a dimension such as attributes.ethnicity.</p>';return targets.map((t,index)=>'<section class="item-card"><div class="panelhead"><h3>'+esc(cohortFieldLabel(t.field))+'</h3>'+(readonly?'':'<div class="row"><button class="button small" data-act="target-edit-saved" data-index="'+index+'">Edit target</button><button class="button small danger" data-act="target-delete" data-index="'+index+'">Remove target</button></div>')+'</div><div class="target-scroll"><table class="target-summary"><thead><tr><th>Group</th><th>Current count</th><th>Current share</th><th>Target count share</th></tr></thead><tbody>'+t.buckets.map(b=>{const count=c.personas.filter(p=>insights.matchesBucket(p,t.field,b)).length;return '<tr><td>'+esc(b.label)+'</td><td>'+count+'</td><td>'+percent(100*count/Math.max(1,c.personas.length))+'</td><td>'+percent(b.percent)+'</td></tr>'}).join('')+'</tbody></table></div></section>').join('')}
function beginTarget(c,custom=false){const field=custom?'attributes.ethnicity':S.distributionField||'age',existing=c.distributionTargets?.find(t=>t.field===field),distribution=insights.distribution(c,field,false),kind=custom?'categorical':distribution.kind;let buckets=distribution.buckets.filter(b=>b.count>0&&(kind!=='numeric'||b.min!==undefined)).map(b=>({label:b.label,percent:Math.round(b.percent*100)/100,...(kind==='numeric'?{min:b.min,max:b.max}:{value:b.value??null})}));if(custom&&!existing)buckets=[];if(!buckets.length)buckets=kind==='numeric'?[{label:'Range',min:18,max:121,percent:100}]:[{label:'Group A',value:'Group A',percent:50},{label:'Group B',value:'Group B',percent:50}];if(buckets.length)buckets[buckets.length-1].percent=Math.round((100-buckets.slice(0,-1).reduce((n,b)=>n+b.percent,0))*100)/100;S.targetOriginalField=existing?.field||null;S.targetDraft=existing?clone(existing):{field,kind,buckets};render()}
function targetEditor(){const t=S.targetDraft;return panel('Edit target distribution','Set percentages totaling 100. These are user targets, not sourced population estimates.','<form data-form="distribution-target"><div class="grid2">'+field('Attribute path','targetField',t.field,'text','Use age, segment, or attributes.country / attributes.ethnicity / another named field.')+select('targetKind',[{value:'numeric',label:'Numeric ranges'},{value:'categorical',label:'Categories'}],t.kind,'Data type')+'</div>'+t.buckets.map((b,i)=>'<div class="target-bucket '+(t.kind==='categorical'?'categorical':'')+'">'+field('Group label','targetLabel'+i,b.label)+ (t.kind==='numeric'?field('From (inclusive)','targetMin'+i,b.min??'','number','','step="any" required')+field('To (exclusive)','targetMax'+i,b.max??'','number','','step="any" required'):field('Attribute value','targetValue'+i,typeof b.value==='string'&& !/^(null|true|false|-?\d+(\.\d+)?|".*")$/.test(b.value)?b.value:JSON.stringify(b.value),'text','Text or JSON scalar. Quote numeric-looking text; null means missing.'))+field('Target %','targetPercent'+i,b.percent,'number','','min="0" max="100" step="any" required')+'<button class="button small danger" type="button" data-act="target-remove-bucket" data-index="'+i+'">Remove</button></div>').join('')+'<p class="subtle">Ranges include “From” and exclude “To”; use 121 as the upper limit to include age 120. Marginal targets do not define correlations between dimensions.</p><div class="row"><button class="button" type="button" data-act="target-add-bucket">Add group</button><button class="button primary" type="button" data-act="target-apply">Apply target</button><button class="button" type="button" data-act="target-cancel">Cancel target edit</button></div></form>')}
function readTargetForm(){const form=root.querySelector('[data-form=distribution-target]');if(!form)return;const d=new FormData(form),t=S.targetDraft;t.field=String(d.get('targetField')||'').trim();t.kind=String(d.get('targetKind'));t.buckets=t.buckets.map((b,i)=>{const base={label:String(d.get('targetLabel'+i)||'').trim(),percent:Number(d.get('targetPercent'+i))};if(t.kind==='numeric')return {...base,min:Number(d.get('targetMin'+i)),max:Number(d.get('targetMax'+i))};const raw=String(d.get('targetValue'+i)||'').trim();let value=raw;if(raw.startsWith('"'))value=jparse(raw,null);else if(raw==='null')value=null;else if(raw==='true'||raw==='false'||/^-?\d+(\.\d+)?$/.test(raw))value=JSON.parse(raw);return {...base,value}})}
function explorerAction(a,el){const c=cohort();if(a==='cohort-section'){S.cohortSection=el.dataset.section;S.personaOpen=false;S.targetDraft=null;render()}
  else if(a==='edit-segment'){S.segmentId=el.dataset.id;render();root.querySelector('.segment-details h3')?.focus()}
  else if(a==='close-segment'){S.segmentId=null;render()}
  else if(a==='persona-back'){S.personaOpen=false;render();root.querySelector('h1')?.focus()}
  else if(a==='persona-step'){const index=c.personas.findIndex(p=>p.id===S.personId);S.personId=c.personas[index+Number(el.dataset.delta)]?.id||S.personId;S.personaRegenOpen=false;render();root.querySelector('h1')?.focus()}
  else if(a==='persona-page'){S.personaPage=Math.max(0,(S.personaPage||0)+Number(el.dataset.delta));render();root.querySelector('h1')?.focus()}
  else if(a==='persona-clear-filter'){S.personaFilter=null;S.personaPage=0;render()}
  else if(a==='persona-sources'){S.personaOpen=false;S.cohortSection='sources';render()}
  else if(a==='persona-regenerate-open'){S.personaRegenOpen=true;S.personaRegenPrompt='';render();void loadLocalAgents()}
  else if(a==='persona-regenerate')startPersonaJob().catch(fail);
  else if(a==='persona-adopt')adoptPersonaProposal();
  else if(a==='persona-job-open'){if(S.localJob?.persona){S.tab='cohorts';S.cohortId=S.localJob.persona.cohortId;S.personId=S.localJob.persona.personaId;S.personaOpen=true;S.personaRegenOpen=true;render()}}
  else if(a==='distribution-drill'){const result=insights.distribution(c,S.distributionField||'age',!!S.distributionWeighted);S.personaFilter={field:S.distributionField||'age',bucket:result.buckets[Number(el.dataset.index)]};S.personaPage=0;S.cohortSection='people';render()}
  else if(a==='target-edit')beginTarget(c);
  else if(a==='target-new')beginTarget(c,true);
  else if(a==='target-edit-saved'){S.targetDraft=clone(c.distributionTargets[Number(el.dataset.index)]);S.targetOriginalField=S.targetDraft.field;render()}
  else if(a==='target-cancel'){S.targetDraft=null;render()}
  else if(a==='target-delete'){c.distributionTargets.splice(Number(el.dataset.index),1);S.dirty=true;S.plan=null;render()}
  else if(a==='target-add-bucket'){readTargetForm();S.targetDraft.buckets.push(S.targetDraft.kind==='numeric'?{label:'New range',min:18,max:25,percent:0}:{label:'New group',value:'New group',percent:0});render()}
  else if(a==='target-remove-bucket'){readTargetForm();S.targetDraft.buckets.splice(Number(el.dataset.index),1);render()}
  else if(a==='target-apply'){const form=root.querySelector('[data-form=distribution-target]');if(!form.reportValidity())return true;readTargetForm();const total=S.targetDraft.buckets.reduce((n,b)=>n+b.percent,0);if(Math.abs(total-100)>0.01)throw Error('Target percentages must total 100%. Current total: '+percent(total)+'.');const targets=[...(c.distributionTargets||[]).filter(t=>t.field!==S.targetDraft.field&&t.field!==S.targetOriginalField),clone(S.targetDraft)];insights.validateTargets(targets);c.distributionTargets=targets;S.targetDraft=null;S.dirty=true;S.plan=null;render();say('Target applied to draft. Save before regeneration.')}
  else return false;return true;
}
`;
