/** Playback reveals saved evaluations only; it never starts or changes inference. */
export const ARENA_CONTROLS_CLIENT = String.raw`
let arenaTimer=0,arenaGeneration=0;
const arenaPlayback={runId:'',stage:'',cursor:undefined,playing:false,speed:1};
function arenaSelectedRun(){return projectRuns().find(r=>r.id===S.liveRunId)||(S.liveRunId!=='history'&&projectRuns().find(r=>r.status==='running'))}
function arenaStage(run){return S.liveStage||(run.liveMembers||[]).find(m=>m.status==='running')?.stage||(run.liveMembers||[]).at(-1)?.stage||run.stages?.[0]?.id||''}
function arenaStop(){clearTimeout(arenaTimer);arenaTimer=0;arenaGeneration++;arenaPlayback.playing=false}
function arenaReset(){arenaStop();arenaPlayback.runId='';arenaPlayback.stage='';arenaPlayback.cursor=undefined}
function arenaOptions(run){const stage=arenaStage(run);if(arenaPlayback.runId!==run.id||arenaPlayback.stage!==stage||run.status==='running'){arenaReset();arenaPlayback.runId=run.id;arenaPlayback.stage=stage}return {replayCursor:arenaPlayback.cursor,replayPlaying:arenaPlayback.playing,replaySpeed:arenaPlayback.speed}}
function arenaMembers(run){return (run.liveMembers||[]).filter(m=>m.stage===arenaStage(run))}
function arenaAdvance(run){const members=arenaMembers(run);arenaPlayback.cursor=Math.min(members.length,(arenaPlayback.cursor||0)+1);const member=members[arenaPlayback.cursor-1];if(member){S.liveMemberKey=member.stage+':'+member.personaId+':'+member.repeat;S.liveMemberPage=Math.floor((arenaPlayback.cursor-1)/24)}if(arenaPlayback.cursor>=members.length)arenaStop()}
function arenaSchedule(){clearTimeout(arenaTimer);const generation=++arenaGeneration;arenaTimer=setTimeout(()=>{if(generation!==arenaGeneration||!arenaPlayback.playing)return;const run=arenaSelectedRun();if(document.visibilityState==='hidden'||S.tab!=='runs'||!run||run.id!==arenaPlayback.runId||arenaStage(run)!==arenaPlayback.stage||run.status==='running'){arenaStop();return}arenaAdvance(run);render();if(arenaPlayback.playing)arenaSchedule()},900/arenaPlayback.speed)}
function arenaAction(action,element){if(!action.startsWith('arena-'))return false;const run=arenaSelectedRun();if(!run||run.status==='running')return true;arenaOptions(run);const total=arenaMembers(run).length;if(!total)return true;if(action==='arena-replay'||action==='arena-reset'){arenaStop();arenaPlayback.cursor=0;S.liveMemberKey='';S.liveMemberPage=0}else if(action==='arena-live'){arenaReset()}else if(action==='arena-step'){arenaStop();arenaAdvance(run)}else if(action==='arena-play'){if(arenaPlayback.playing)arenaStop();else{if(arenaPlayback.cursor===undefined||arenaPlayback.cursor>=total){arenaPlayback.cursor=0;S.liveMemberKey='';S.liveMemberPage=0}arenaPlayback.playing=true;arenaSchedule()}}else if(action==='arena-scrub'){arenaStop();arenaPlayback.cursor=Math.max(0,Math.min(total,Number(element.value)||0));const member=arenaMembers(run)[Math.max(0,arenaPlayback.cursor-1)];S.liveMemberKey=member?member.stage+':'+member.personaId+':'+member.repeat:'';S.liveMemberPage=Math.floor(Math.max(0,arenaPlayback.cursor-1)/24)}else if(action==='arena-speed'){const speed=Number(element.dataset.speed);if([.5,1,2,4].includes(speed))arenaPlayback.speed=speed;if(arenaPlayback.playing)arenaSchedule()}render();return true}
document.addEventListener('change',event=>{if(event.target.matches?.('[data-arena-scrub]'))arenaAction('arena-scrub',event.target)});
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden'){arenaStop();if(S.tab==='runs'&&S.snap)render()}});
`;
