/** Shared drafting status. Counts come from validated server output, never a timer. */
export const DRAFT_PROGRESS_CSS = `
.draft-progress{padding:24px}.draft-progress-heading{display:flex;justify-content:space-between;gap:16px;align-items:start}.draft-progress-actions{display:flex;align-items:center;justify-content:flex-end;gap:12px;flex-wrap:wrap}.draft-progress h2{font-size:18px}.draft-provider{margin:5px 0 0;color:var(--muted);font-size:12px;overflow-wrap:anywhere}.draft-elapsed{color:var(--muted);font-size:12px;white-space:nowrap;font-variant-numeric:tabular-nums}.draft-count{margin:22px 0 8px;font-size:13px;color:var(--muted)}.draft-count strong{font-size:27px;font-weight:650;letter-spacing:-.04em;color:var(--ink);font-variant-numeric:tabular-nums}.draft-progress progress{display:block;width:100%;height:8px;border:0;border-radius:8px;overflow:hidden;appearance:none;background:var(--line);accent-color:var(--teal)}.draft-progress progress::-webkit-progress-bar{background:var(--line);border-radius:8px}.draft-progress progress::-webkit-progress-value{background:var(--teal);border-radius:8px}.draft-progress progress::-moz-progress-bar{background:var(--teal);border-radius:8px}.draft-progress-status{margin:20px 0 4px;font-size:14px;font-weight:650}.draft-progress-detail{margin:0;color:var(--muted);font-size:12px}.draft-steps{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px;list-style:none;padding:20px 0;margin:0}.draft-steps li{border-top:2px solid var(--line);padding-top:9px;color:var(--faint);font-size:12px}.draft-steps li[data-state=done]{border-color:var(--teal);color:var(--teal)}.draft-steps li[data-state=current]{border-color:var(--blue);color:var(--ink);font-weight:650}.draft-progress-note{margin:0;color:var(--muted);font-size:12px}.draft-progress-error{margin-top:16px}.draft-progress-error .button{margin-top:8px}@media(max-width:540px){.draft-progress{padding:18px}.draft-progress-heading{flex-wrap:wrap}.draft-progress-actions{width:100%;justify-content:space-between}.draft-count{margin-top:16px}.draft-steps{gap:8px}}
`;

export const DRAFT_PROGRESS_CLIENT = String.raw`
function draftCancelButton(job){return job?.id&&job.status==='running'?'<button class="button" type="button" data-act="assistant-cancel">Cancel generation</button>':''}
function draftElapsed(start,end){const seconds=Math.max(0,Math.floor(((end?Date.parse(end):Date.now())-Date.parse(start))/1000));if(!Number.isFinite(seconds))return '';const minutes=Math.floor(seconds/60);return (minutes?minutes+'m ':'')+(seconds%60)+'s elapsed'}
function updateDraftClocks(){root.querySelectorAll('[data-draft-start]').forEach(node=>{node.textContent=draftElapsed(node.dataset.draftStart)})}
function draftProgress(job){
  const p=job.progress||{},phase=p.phase||'generating',total=p.totalPersonas,completed=p.completedPersonas;
  const provider=job.engine==='chatgpt'?'ChatGPT':job.engine==='claude'?'Claude Code':'Codex';
  const finishing=phase==='validating'&&(!p.totalBatches||p.completedBatches===p.totalBatches);
  const step=phase==='saving'||phase==='checking'?0:finishing?2:1;
  const title=job.cohort?'Generating '+job.cohort.size.toLocaleString('en-US')+' personas':job.persona?'Generating replacement persona':'Preparing your proposal';
  const status=phase==='saving'?'Saving your latest edits':phase==='checking'?'Checking AI connection':finishing?'Checking the complete draft':phase==='validating'?'Checking batch '+p.batch+' of '+p.totalBatches:p.batch?'Generating batch '+p.batch+' of '+p.totalBatches:'Creating your draft';
  const detail=phase==='saving'?'Generation starts automatically after saving.':phase==='checking'?'Confirming that your selected provider is ready.':finishing?'Validating structure, references, and any cohort targets before review.':phase==='validating'?'Checking the returned personas before adding them to the draft.':'Waiting for '+provider+' to return '+(p.batch?'this batch.':'the draft.')+' Counts update after validation.';
  const counts=Number.isFinite(total)&&Number.isFinite(completed)?'<div class="draft-count"><strong>'+completed.toLocaleString('en-US')+' / '+total.toLocaleString('en-US')+'</strong> personas checked</div><progress aria-label="Personas checked" value="'+completed+'" max="'+total+'"></progress>':'';
  const steps=['Prepare','Generate & check','Final checks'].map((label,i)=>'<li data-state="'+(i<step?'done':i===step?'current':'pending')+'"'+(i===step?' aria-current="step"':'')+'>'+(i<step?'✓ ':String(i+1)+'. ')+label+'</li>').join('');
  return '<section class="panel draft-progress" aria-label="Generation progress"><div class="draft-progress-heading"><div><h2>'+esc(title)+'</h2><p class="draft-provider">'+esc(provider+(job.model?' · '+job.model:''))+'</p></div><div class="draft-progress-actions">'+(job.startedAt?'<span class="draft-elapsed" data-draft-start="'+attr(job.startedAt)+'">'+esc(draftElapsed(job.startedAt))+'</span>':'')+draftCancelButton(job)+'</div></div>'+counts+'<div role="status" aria-live="polite"><p class="draft-progress-status">'+esc(status)+'</p><p class="draft-progress-detail">'+esc(detail)+'</p>'+(Number.isFinite(p.completedBatches)?'<p class="subtle">'+p.completedBatches+' of '+p.totalBatches+' batches checked</p>':'')+'</div><ol class="draft-steps" aria-label="Generation steps">'+steps+'</ol>'+(S.localPollError?'<div class="warning draft-progress-error" role="alert">Status connection interrupted. Generation may still be running.<br>'+esc(S.localPollError)+'<br><button class="button" data-act="assistant-status-retry">Reconnect progress</button></div>':'')+'<p class="draft-progress-note">Review the finished draft before replacing any personas or study.</p></section>';
}
`;
